werkzeug - INFO -  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
werkzeug - INFO - 127.0.0.1 - - [09/Mar/2020 22:24:52] "GET /isalive HTTP/1.1" 200 -
main - ERROR - Exception on /isalive [GET]
Traceback (most recent call last):
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "main.py", line 17, in get
    app.logging.info("Ho")
AttributeError: 'Flask' object has no attribute 'logging'
main - ERROR - Exception on /isalive [GET]
Traceback (most recent call last):
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "main.py", line 17, in get
    app.logging.info("Ho")
AttributeError: 'Flask' object has no attribute 'logging'
main - ERROR - Exception on /isalive [GET]
Traceback (most recent call last):
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "main.py", line 17, in get
    app.logging.info("Ho")
AttributeError: 'Flask' object has no attribute 'logging'
main - ERROR - Exception on /isalive [GET]
Traceback (most recent call last):
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "main.py", line 17, in get
    app.logging.info("Ho")
AttributeError: 'Flask' object has no attribute 'logging'
main - ERROR - Exception on /isalive [GET]
Traceback (most recent call last):
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "main.py", line 17, in get
    class IsAlive(Resource):
AttributeError: 'Flask' object has no attribute 'logging'
main - ERROR - Exception on /training/ [GET]
Traceback (most recent call last):
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/shazbyte/anaconda3/envs/katana/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "main.py", line 30, in get
    app.logging.info("Ho")
AttributeError: 'Flask' object has no attribute 'logging'
